### ISSUE TITLE
Not compatable with servers. 

### ISSUE THREAD

**Issue by Runburner** [asiekierka/littleMaidMobX#3]
Kuro had told me to try your mod version to get the maids skins working on my server but the instant that I inserted the mod and restarted the server i was given an instant crash. Something to do with textures. I'll need your email to send the crashlogs as I cant export them from the server they are on.

**Comment by KuroNeko87** [comment]
The problem seems to be in here 
https://github.com/asiekierka/littleMaidMobX/blob/master/src/main/java/mmmlibx/lib/MMM_TextureManager.java#L540

Here's part of the stacktrace.
https://gist.github.com/KuroNeko87/3f1108adecb16c3a239d

**Comment by KuroNeko87** [comment]
Made 2 PRs, not sure if they're working. Currently building and testing
https://github.com/asiekierka/littleMaidMobX/pull/4
https://github.com/asiekierka/littleMaidMobX/pull/5

**Comment by EndridTelek** [comment]
Um alright. Hopefuly that gets the skins working on server side. :)

**Comment by KuroNeko87** [comment]
grrr not working

**Comment by KuroNeko87** [comment]
oh wait, i didn't implement the fixed, i just build from asie's source... duh

**Comment by EndridTelek** [comment]
Ugh, I can't wait to learn Java so I can help with this mod. I love it so much.

**Comment by EndridTelek** [comment]
XD FAIL

**Comment by KuroNeko87** [comment]
yup, not working. I'm missing something but don't know what it is

**Comment by KuroNeko87** [comment]
I do know the problem is the old model loader asie added, something's off in it but asie is not available right now, tried to message him on irc

**Comment by EndridTelek** [comment]
Irc? And ok. but about the server, wouldnt it be that server needs Modchu? cause LMMAX works client side but not server side.

**Comment by KuroNeko87** [comment]
no, modchu is something different from the LMM. modchu is a library for playerformlittlemaid, but you can load the models for littlemaidmob.

for now try the version in here http://forum.minecraftuser.jp/viewtopic.php?t=23347 
The big littleMaidMobX-1.7.x_0.0.9.jar

**Comment by EndridTelek** [comment]
Use that for the server and see if skins work? Cause I am using your build right now.

**Comment by KuroNeko87** [comment]
yeah, my build doesnt have the server texture fixes. I stopped developing it midway because i still don't have the skills necessary.

**Comment by EndridTelek** [comment]
Ah, ok. Thanks for the help. When i start learning java, I'd be more then happy to help you work with it. Sound fun?

**Comment by asiekierka** [comment]
I know about this bug, however I have never had time to fix it - I spend most of my time working on BuildCraft

**Comment by EndridTelek** [comment]
oh >-< I would really like it fixed, wanting to start a let's play with my server and friends soon. I love the mod alot. Or is that 9 version have everything ready to work?

**Comment by asiekierka** [comment]
That 9 version has some things working better than ours and some not. I will look into it right now, OK?

**Comment by EndridTelek** [comment]
Sure. Thanks. I will be learning Java soon, and I work alot with mods and Minecraft, so I'll most likely join you guys in deving the mod. :)

**Comment by asiekierka** [comment]
@Runburner - test this: http://asie.pl/lmmax-test1.jar - should have sounds fixed as well.

**Comment by EndridTelek** [comment]
alright. Will do, applying to server now.

**Comment by EndridTelek** [comment]
So far FML shows no errors on server or Client startup. I will test sound and skins, now.

**Comment by EndridTelek** [comment]
Something went wrong in that. All maids despawned, and now i cant even spawn them. It's throwing some error on the server. A single player world is just getting stuck loading now.

**Comment by asiekierka** [comment]
What error?

**Comment by EndridTelek** [comment]
[02:48:41] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Lotus Realm_New Horizon
[02:49:06] [Server thread/DEBUG] [FML/]: The world 242f5344 (Lotus Realm_New Horizon) may have leaked: seen 25 times.

[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mmmlibx.lib.MMM_TextureData.getTextureName(MMM_TextureData.java:377)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.setTexturePackName(LMM_EntityLittleMaid.java:3214)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.<init>(LMM_EntityLittleMaid.java:231)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.spawnMaid(LMM_ItemSpawnEgg.java:129)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.func_77648_a(LMM_ItemSpawnEgg.java:49)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.item.ItemStack.func_77943_a(Unknown Source)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[02:49:10] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mmmlibx.lib.MMM_TextureData.getTextureName(MMM_TextureData.java:377)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.setTexturePackName(LMM_EntityLittleMaid.java:3214)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.<init>(LMM_EntityLittleMaid.java:231)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.spawnMaid(LMM_ItemSpawnEgg.java:129)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.func_77648_a(LMM_ItemSpawnEgg.java:49)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.item.ItemStack.func_77943_a(Unknown Source)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mmmlibx.lib.MMM_TextureData.getTextureName(MMM_TextureData.java:377)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.setTexturePackName(LMM_EntityLittleMaid.java:3214)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.<init>(LMM_EntityLittleMaid.java:231)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.spawnMaid(LMM_ItemSpawnEgg.java:129)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.func_77648_a(LMM_ItemSpawnEgg.java:49)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.item.ItemStack.func_77943_a(Unknown Source)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[02:49:12] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mmmlibx.lib.MMM_TextureData.getTextureName(MMM_TextureData.java:377)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.setTexturePackName(LMM_EntityLittleMaid.java:3214)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.<init>(LMM_EntityLittleMaid.java:231)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.spawnMaid(LMM_ItemSpawnEgg.java:129)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.func_77648_a(LMM_ItemSpawnEgg.java:49)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.item.ItemStack.func_77943_a(Unknown Source)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[02:49:26] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Lotus Realm_New Horizon
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mmmlibx.lib.MMM_TextureData.getTextureName(MMM_TextureData.java:377)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.setTexturePackName(LMM_EntityLittleMaid.java:3214)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.<init>(LMM_EntityLittleMaid.java:231)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.spawnMaid(LMM_ItemSpawnEgg.java:129)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.func_77648_a(LMM_ItemSpawnEgg.java:49)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.item.ItemStack.func_77943_a(Unknown Source)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[02:49:26] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mmmlibx.lib.MMM_TextureData.getTextureName(MMM_TextureData.java:377)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.setTexturePackName(LMM_EntityLittleMaid.java:3214)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.<init>(LMM_EntityLittleMaid.java:231)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.spawnMaid(LMM_ItemSpawnEgg.java:129)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.func_77648_a(LMM_ItemSpawnEgg.java:49)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.item.ItemStack.func_77943_a(Unknown Source)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at mmmlibx.lib.MMM_TextureData.getTextureName(MMM_TextureData.java:377)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.setTexturePackName(LMM_EntityLittleMaid.java:3214)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_EntityLittleMaid.<init>(LMM_EntityLittleMaid.java:231)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.spawnMaid(LMM_ItemSpawnEgg.java:129)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at littleMaidMobX.LMM_ItemSpawnEgg.func_77648_a(LMM_ItemSpawnEgg.java:49)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.item.ItemStack.func_77943_a(Unknown Source)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[02:49:27] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by asiekierka** [comment]
Just to make sure what's wrong, try doing it _without_ any additional skins installed. (Or send me your modpack and wait a few hours. Need to get some things done.)

**Comment by EndridTelek** [comment]
alright. Where can I include the whole log, if you want to review it?

**Comment by asiekierka** [comment]
I don't need to

**Comment by KuroNeko87** [comment]
I wish i could do more T_T

**Comment by asiekierka** [comment]
Shh. No tears, only dreams now.

**Comment by EndridTelek** [comment]
Nope, same thing.

**Comment by EndridTelek** [comment]
The japan form V9 is not working either. Maids will work but if a non vanilla skin is selected and you tp away, Sever says that the entity is try to Write State and will not persist, and the maid disappears. I guess I will have to do with resetting the skins every time. No worries. Just let me know when you  guys make a fix. Thanks for the help and everything, If i get anymore bugs, I'll make sure to post to help with dev.
